Repository mobileappdevhm19/campus-connected-team-6, pull requests merged in 2019-07, with the labels that each got.

#93 Fix profile and login sign up page
  lib/FAQ/data.dart
  lib/helper/authentication.dart
  lib/main.dart
  lib/models/dashboard_item.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/event_users_list.dart
  lib/pages/login_signup_page.dart
  lib/pages/password_reset.dart
  lib/pages/profile.dart
  lib/pages/search_events.dart
  lib/pages/signup_page.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/pages/view_event.dart
  lib/pages/welcome_page.dart
  lib/services/authentication.dart
  lib/utils/screen_aware_size.dart
  lib/utils/text_aware_size.dart
  pubspec.lock
  pubspec.yaml
  test/profile_test.dart
  test/signup_page_test.dart
Labels: fix

#95 searchProfileNavbar
  lib/main.dart
  lib/pages/users_profile.dart
  test/users_profile_test.dart
Labels: feature

#96 Profile
  lib/helper/cloud_firestore_helper.dart
  lib/pages/users_profile.dart
Labels: help wanted

#97 Fix profile create event
  lib/helper/cloud_firestore_helper.dart
  lib/models/user_entity.dart
  lib/models/user_entity_add.dart
  lib/models/user_model.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/event_users_list.dart
  lib/pages/profile.dart
  lib/pages/search_events.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/pages/view_event.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
Labels: fix

#98 Fix sign up page
  lib/pages/signup_page.dart
  lib/pages/usersProfileDetails.dart
  test/signup_page_test.dart
Labels: fix

#99 Feature settings page
  lib/main.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/faq_page.dart
  lib/pages/login_signup_page.dart
  lib/pages/profile.dart
  lib/pages/usersProfileDetails.dart
  lib/settings/color_box.dart
  lib/settings/settings.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#100 fix for last commit
  lib/pages/login_signup_page.dart
Labels: fix

#101 Fixes for User storage. New User model added. Code formatted
  lib/helper/cloud_firestore_helper.dart
  lib/logos/campus_logo.dart
  lib/main.dart
  lib/models/user_entity.dart
  lib/models/user_entity_add.dart
  lib/models/user_model.dart
  lib/pages/edit_profile.dart
  lib/pages/event_users_list.dart
  lib/pages/profile.dart
  lib/pages/signup_page.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/pages/view_event.dart
  lib/settings/color_box.dart
  lib/settings/settings.dart
  test/edit_profile_test.dart
  test/profile_test.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
Labels: feature, fix

#102 More tests
  test/event_users_list_test.dart
  test/password_reset_test.dart
  test/signup_page_test.dart
Labels: fix

#103 Update user_model.dart
  lib/models/user_model.dart
Labels: fix

#104 Update README.md
  README.md
Labels: fix

#105 Login/registration fixed and adjusted. User participations fixed. The…
  lib/main.dart
  lib/models/user_model.dart
  lib/pages/dashboard.dart
  lib/pages/event_users_list.dart
  lib/pages/login_signup_page.dart
  lib/pages/password_reset.dart
  lib/pages/profile.dart
  lib/pages/search_events.dart
  lib/pages/signup_page.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/settings/settings.dart
  pubspec.yaml
  test/event_model_test.dart
  test/search_events_test.dart
  test/user_model_test.dart
Labels: fix

#107 Add privacy policy
  lib/helper/cloud_firestore_helper.dart
  lib/main.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/event_users_list.dart
  lib/pages/faq_page.dart
  lib/pages/privacy_policy.dart
  lib/pages/profile.dart
  lib/pages/signup_page.dart
  lib/pages/splash_screen.dart
  lib/pages/view_event.dart
  pubspec.lock
  pubspec.yaml
  test/faq_page_test.dart
  test/privacy_policy_test.dart
  test/user_model_test.dart
Labels: fix
