Repository mobileappdevhm19/campus-connected-team-6, pull requests merged in 2019-06, with the labels that each got.

#42 Feature initial implementation create event event view event list event search dashboard
  ios/GoogleService-Info.plist
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/GoogleService-Info.plist
  ios/Runner/Info.plist
  lib/helper/cloud_firestore_helper.dart
  lib/main.dart
  lib/models/event_model.dart
  lib/models/event_user_model.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/event_users_list.dart
  lib/pages/home_page.dart
  lib/pages/login_signup_page.dart
  lib/pages/search_events.dart
  lib/pages/view_event.dart
  pubspec.yaml
  test/testHelper.dart
Labels: feature

#45 initial implementation for issues: 37 and 38
  lib/pages/dashboard.dart
Labels: feature

#46 fix for issues 37 and 38
  lib/pages/edit_profile.dart
  lib/pages/profile.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
Labels: fix

#47 Navbar&Rooting
  .travis.yml
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com.jcontrer.flutter_campus_connected/MainActivity.java
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/profile/AndroidManifest.xml
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  lib/main.dart
  lib/pages/create_event.dart
  lib/pages/dashboard.dart
  lib/pages/event_users_list.dart
  lib/pages/login_signup_page.dart
  lib/pages/search_events.dart
  lib/pages/signup_page.dart
  lib/root_page.dart
  pubspec.yaml
Labels: feature

#44 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#49 manifest adjusted. Build.gradle updated. Removed useless code
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  lib/main.dart
  lib/pages/login_signup_page.dart
  lib/root_page.dart
Labels: fix

#50 implementation for issues 35 and 36 and widget tests
  lib/logos/campus_logo.dart
  lib/logos/login_logo.dart
  lib/main.dart
  lib/pages/dashboard.dart
  lib/pages/login_signup_page.dart
  lib/pages/splash_screen.dart
  lib/pages/welcome_page.dart
  test/campusLogo_test.dart
  test/loginLogo_test.dart
  test/splashScreen_test.dart
  test/welcomePage_test.dart
Labels: feature

#55 Widget test implementation
  lib/pages/profile.dart
  lib/pages/usersProfileDetails.dart
  pubspec.lock
  pubspec.yaml
  test/LoginSignupPage_test.dart
  test/MyForm_test.dart
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/profile_test.dart
  test/splash_screen_test.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
  test/welcome_page_test.dart
Labels: feature

#58 Widget test implementation
  lib/pages/users_profile.dart
  test/users_profile_test.dart
Labels: feature

#59 reformat code
  lib/logos/campus_logo.dart
  lib/logos/login_logo.dart
  lib/pages/profile.dart
  lib/pages/splash_screen.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/pages/welcome_page.dart
  test/campusLogo_test.dart
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/loginLogo_test.dart
  test/profile_test.dart
  test/splash_screen_test.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
  test/welcome_page_test.dart
Labels: feature

#61 tests added for master
  lib/pages/login_signup_page.dart
  test/campusLogo_test.dart
  test/create_event_test.dart
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/loginLogo_test.dart
  test/myHomepage.dart
  test/profile_test.dart
  test/splash_screen_test.dart
  test/test_helper.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
  test/view_event_test.dart
  test/welcome_page_test.dart
Labels: feature

#64 Feature flutter launcher icons
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
  pubspec.yaml
Labels: feature

#65 ios_config_auskommentiert
  .travis.yml
Labels: bug

#67 More widget tests
  test/create_event_test.dart
  test/event_model_test.dart
  test/event_user_model_test.dart
  test/search_events_test.dart
  test/view_event_test.dart
Labels: feature

#70 Weitere tests und integration test by tamara
  lib/models/event_entity.dart
  lib/models/user_entity.dart
  lib/models/user_model.dart
  lib/pages/dashboard.dart
  lib/pages/login_signup_page.dart
  lib/pages/signup_page.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  test/usersProfileDetails_test.dart
  test/users_profile_test.dart
  test_driver/app.dart
  test_driver/app_test.dart
Labels: feature

#73 Feature event view participant list displaying profile pictures
  lib/pages/event_users_list.dart
  lib/pages/login_signup_page.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/view_event.dart
  test/usersProfileDetails_test.dart
Labels: feature

#74 Pop up Message für Create Event hinzugefügt
  lib/pages/create_event.dart
  test/create_event_test.dart
Labels: feature

#79 Fix commit for event and profile pages
  lib/main.dart
  lib/pages/dashboard.dart
  lib/pages/event_users_list.dart
  lib/pages/faq_page.dart
  lib/pages/splash_screen.dart
  lib/pages/usersProfileDetails.dart
  lib/pages/users_profile.dart
  lib/pages/view_event.dart
  test/users_profile_test.dart
  test/view_event_test.dart
Labels: fix

#81 Weitere tests und integration test by tamara
  lib/mock/cloud_firestore_helper_mock.dart
  lib/mock/firebase_user_mock.dart
  lib/models/dashboard_item.dart
  lib/models/profile_item.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/profile.dart
  pubspec.lock
  pubspec.yaml
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/profile_test.dart
  test/test_helper.dart
Labels: feature

#82 initial commit
  lib/main.dart
  lib/pages/profile.dart
  lib/pages/search_events.dart
  lib/pages/splash_screen.dart
Labels: feature

#83 Hot fix for master branch after unsuccesfully merge from old branch s…
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/faq_page.dart
  lib/pages/profile.dart
  lib/pages/search_events.dart
  test/create_event_test.dart
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/faq_page_test.dart
  test/profile_test.dart
  test/test_helper.dart
Labels: fix

#87 New navbar with 4 icons
  lib/FAQ/faq_questions.dart
  lib/main.dart
  lib/mock/cloud_firestore_helper_mock.dart
  lib/mock/firebase_user_mock.dart
  lib/models/dashboard_item.dart
  lib/models/profile_item.dart
  lib/pages/profile.dart
Labels: feature

#90 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: feature

#89 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: feature

#88 Update README.md
  README.md
Labels: feature

#91 Update LICENSE
  LICENSE
Labels: feature

#92 Create PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: feature

#84 zur profile page neue Felder hinzugefügt plus ein paar tests
  .travis.yml
  lib/FAQ/data.dart
  lib/helper/cloud_firestore_helper.dart
  lib/models/user_entity_add.dart
  lib/pages/dashboard.dart
  lib/pages/edit_profile.dart
  lib/pages/profile.dart
  lib/pages/splash_screen.dart
  pubspec.yaml
  test/create_event_test.dart
  test/dashboard_test.dart
  test/edit_profile_test.dart
  test/faq_page_test.dart
  test/loginLogo_test.dart
  test/login_signup_page_test.dart
  test/myHomepage.dart
  test/profile_test.dart
  test/search_events_test.dart
  test/signup_page_test.dart
  test/splash_screen_test.dart
  test/usersProfileDetails_test.dart
  test/welcome_page_test.dart
  test_driver/app.dart
Labels: feature
